### ISSUE TITLE
hugo-cli integration

### ISSUE THREAD

**Issue by levidrain** [jbrodriguez/hugulp#17]
Love the tool! So much easier than setting it all up from scratch.

Have you considered integration hugo-cli?  I'm on Windows and it's the only link in the chain that requires manual set up.

**Comment by jbrodriguez** [comment]
Thanks for the comments @levidrain.

It's not easy to integrate because they're built on different platforms (go vs node).

Having said that, I'm always looking to replace gulp (a most importantly the plugins) with a go-based tool.

That would make it trivial to integrate.

But I haven't found go libraries/packages comparable (and up-to-date) to gulp-sass, gulp-rev, etc.

It can definitely be done in go, but there's no such ecosystem currently available (that I know of at least).

**Comment by levidrain** [comment]
My background isn't in node or even go for that matter.  But I guess I was thinking it would be trivial. There's an Npm wrapper around hugo already. If it were listed as a dependency, then it would be available on the command line and your current setup would just work the way it does now.

**Comment by jbrodriguez** [comment]
Ok, to get a better idea, how do you picture the integration ?
Or what are you proposing ?
Just trying to figure out what you're thinking :)

**Comment by levidrain** [comment]
To use hugulp now (at least on windows) you have to separately download hugo.exe and make sure it's in your path. This means picking the right execute for your system, renaming it to hugo.exe and adding the folder it's in to the path. 
But hugulp already uses Npm to get install. If the hugo-cli package were listed in the packages js file, it would be pulled down when hugulp is installed, right. Which (I think) mean hugulp would just work with the need for the cumbersome steps listed above.

**Comment by jbrodriguez** [comment]
Ok, now I see where you're coming from 👍 

I'd probably not default to make hugulp install hugo, as it's likely that it was already installed.

I'll give it some thought and come back with a proposal.
